### ISSUE TITLE
Publishing Exredis to hex.pm

### ISSUE THREAD

**Issue by whatyouhide** [artemeff/exredis#24]
[hex.pm](https://hex.pm) is a very useful hub where you can publish Elixir (and Erlang) packages. It's what Mix dependencies use by default, so if you publish your package to Hex you can then list it as a dependency just as:

```elixir
[{:exredis, "~> 0.4.0"}]
```

instead of using the GitHub url. You can also host documentation on Hex (like *a lot* of packages are doing now) with the `mix hex.docs` task.

What do you think?

**Comment by artemeff** [comment]
Yep, but exredis dependent on eredis, which is not on hex.pm, and used as git dependency:

> Only Hex packages will be included as dependencies of the package, for example Git dependencies will not be included.
> – from [Hex.pm documentation](https://hex.pm/docs/publish)

**Comment by whatyouhide** [comment]
Oh man, I completely missed that. Makes perfect sense :) Sorry then, and thanks for the swift response!
