### ISSUE TITLE
Exredis.query() without client parameter. (using defaultclient)

### ISSUE THREAD

**Issue by hey-jude** [artemeff/exredis#27]
Exredis.Api has no-client parameter methods using defaultclient, but Exredis.query() doesn't.

**Comment by artemeff** [comment]
I did it, because `query` function must be raw, for low-level querying.
API contains functions that we can execute without client argument for simple cases, like unit tests.
But you can implement it, if you want.

**Comment by hey-jude** [comment]
Then, how about changing "defaultclient" to public member?
(current defaultclient is private.)

**Comment by artemeff** [comment]
Yep, you can implement it, I will accept your PR.
