### ISSUE TITLE
HMGET / HMSET example

### ISSUE THREAD

**Issue by ktodyruik** [artemeff/exredis#36]
Hi,

This looks great. I was looking for a good persistence option for Elixir. Are there any examples of HMSET/HMGET with exredis? If not, could you add one?

Thanks,
Kerry

**Comment by lastcanal** [comment]
There are a few examples in the API Tests https://github.com/artemeff/exredis/blob/master/test/api_test.exs#L293-L303

**Comment by ktodyruik** [comment]
Oh. Sorry. I looked through those but missed them somehow.

Thanks!
Kerry
