### ISSUE TITLE
Do not provide use ExRedis

### ISSUE THREAD

**Issue by josevalim** [artemeff/exredis#41]
If all `use ExRedis` does is to import functions, then please don't provide it at all. Simply tell users to `import ExRedis` instead.

The reason is because I always know what `import ExRedis` does and how to configure it. I have no idea what "use ExRedis" will do and I often assume it does more than simply import.

**Comment by artemeff** [comment]
Fixed in a08e229c55ade9be2b7cc3516cdd27b13b9828cc, thanks!
