### ISSUE TITLE
docker: how to configure endpoint of redis server via the System.get_env

### ISSUE THREAD

**Issue by markpoon** [artemeff/exredis#42]
I'm having some trouble with configuring where the redis server will be at runtime when running it inside containers, I want to configure it by passing it a connection string like:

`client = Exredis.start_using_connection_string(System.get_env("REDIS_PORT_6379_TCP") || "redis://127.0.0.1:6379") `

I'm expecting REDIS_PORT_6379_TCP to be "tcp:///123.123.123.123:1234"

but I'm not sure how exactly to do that with elixir (apologies, still learning) I've seen some systems expect these variables in config/config.exs, would that be where they would go?

**Comment by artemeff** [comment]
@markpoon you can use connection string https://github.com/artemeff/exredis/blob/master/lib/exredis.ex#L12, there's no tcp, btw, only `redis://` :)
