### ISSUE TITLE
Exredis.Api.incr cannot parse reply as int when used in transaction

### ISSUE THREAD

**Issue by avdgaag** [artemeff/exredis#44]
When using a transaction, all commands return "QUEUED". `Exredis.Api` will try to parse that as an integer and fail.

For example, this won't work:

```ex
Exredis.Api.multi
Exredis.Api.incr "my_key"
Exredis.Api.exec
```

My current work-around is:

```ex
Exredis.Api.multi
# ... other statements
Exredis.query(Exredis.Api.defaultclient, ["INCR", id])
Exredis.Api.exec
```

My suggestion would be to not to do auto-parsing at all, but make it clear that you can use these callback functions yourself if you want to. So if you _do_ want to auto-parse, you'd do `Exredis.Api.inc "my_key", &Exredis.Api.int_reply/1`, and if not, you'd omit the callback function.

**Comment by artemeff** [comment]
Hi! Thanks for the bug report.

I think we can create something like `maybe_int_reply`, where we just handle exceptions and return original binary data when something went wrong.

Later, I'll write some benchmarks for this client and think about exceptions catching.

**Comment by artemeff** [comment]
Sorry for late fixing, there is no performance degradation with try/catch in this place, works well and `exec` returns raw binaries.
