### ISSUE TITLE
warning: the dependency :exredis requires Elixir "~> 1.0.0" but you are running on v1.1.1

### ISSUE THREAD

**Issue by davidmoshal** [artemeff/exredis#47]
Wondering how best to handle this (OSX):

`warning: the dependency :exredis requires Elixir "~> 1.0.0" but you are running on v1.1.1`

**Comment by artemeff** [comment]
@davidmoshal what version do you use? @kwojtaszek [fixed it](https://github.com/appunite/exredis/commit/7939e7fe634ea8f85c742fb494b0488798b8e72e#diff-6023be6004fce4718dad3dafb576d258L9) in master branch.

**Comment by kwojtaszek** [comment]
@davidmoshal I can confirm that current master branch works correctly with exredis, so either use master branch or wait for exredis release

**Comment by davidmoshal** [comment]
@artemeff Yuri: I'm just running `mix deps.get`
From the Exredis.Mixfile it looks like version 0.2.0: 

```
defmodule Exredis.Mixfile do
  use Mix.Project

  def project do
    [ app: :exredis,
      version: "0.2.0",
      elixir: "~> 1.0.0",
      name: "exredis",
      source_url: "https://github.com/artemeff/exredis",
      homepage_url: "http://artemeff.github.io/exredis",
      deps: deps,
      package: package,
      description: "Redis client for Elixir",
      docs: [readme: true, main: "README.md"] ]
  end

  # Configuration for the OTP application
  def application do
    [applications: [:eredis]]
  end

  # Dependencies
  defp deps do
    [{:eredis,  ">= 1.0.8"}]
  end

  defp package do
    [
      contributors: ["Yuri Artemev", "Joakim Kolsjö", "lastcanal", "Aidan Steele",
        "Andrea Leopardi", "Ismael Abreu", "David Rouchy", "David Copeland",
        "Psi", "Andrew Forward", "Sean Stavropoulos"],
      licenses: ["MIT"],
      links: %{"GitHub" => "https://github.com/artemeff/exredis"}
    ]
  end
end
```

**Comment by davidmoshal** [comment]
@kwojtaszek Is there a way to specify master branch with Mix?
Or, do I manually download Exredis master branch and copy it to deps directory?
Thanks
Dave
ps: am new to Elixir, trying it out on existing app which uses Redis pubsub to route json messages between NodeJS and Groovy applications.

**Comment by artemeff** [comment]
@davidmoshal yup.

```elixir
defp deps do
  [{:exredis, github: "artemeff/exredis"}]
end
```

**Comment by davidmoshal** [comment]
Thanks, works for me.
Great dependency management system.
