### ISSUE TITLE
Do not promote Exredis.start in the README

### ISSUE THREAD

**Issue by josevalim** [artemeff/exredis#48]
Folks should not depend on Exredis.start because it may leave dangling connections. Imagine you are calling `Exredis.start` inside a GenServer init. Because the processes are not connected, every time the GenServer crashes, you will have a dangling Exredis connection process that will never be reclaimed. We should only promote two ways, really:

  1. Starting Exredis as part of a supervision tree (using start_link)
  2. Starting Exredis using start_link directly

**Comment by artemeff** [comment]
@josevalim thanks for your thoughts, but `Exredis.start` is just alias to `start_link` that returns pid, and all started clients automatically connect to parent process, or you just want to `s/start/start_link/` in the readme? :)

**Comment by josevalim** [comment]
Oops, sorry! I think this exposes another issue. The Elixir and OTP convention is that `start` returns `{:ok, pid}`, similar to `start_link`, except `start` does not link the processes.

So how to move next is up to you. I would possibly deprecate `start` and leave `start_link` as the official way of doing things. Your call and thanks for checking this!

**Comment by artemeff** [comment]
@josevalim how can I deprecate this method? Simply notify to `IO.puts` with stderr about deprecation? :)

**Comment by josevalim** [comment]
Something like: `IO.write :stderr, "warning: oops\n" <> Exception.format_stacktrace`
