### ISSUE TITLE
New release with fixed warnings

### ISSUE THREAD

**Issue by rodrigues** [artemeff/exredis#77]
I've noticed `master` does not raise any of the [151 elixir compilation warnings](https://gist.githubusercontent.com/rodrigues/c0bd4b8e6ee68e5d966912f3ad85bfa5/raw/6a2019563c0300a50822c8fdc2ed2ba6592e74e5/exredis-compile.log) we get when compiling latest hex version on elixir 1.6.

Could we have a new release please?

Thanks!

**Comment by kirillshevch** [comment]
+1

**Comment by artemeff** [comment]
0.2.6 is on hex https://hex.pm/packages/exredis
