### ISSUE TITLE
Multiple connections?

### ISSUE THREAD

**Issue by Stratus3D** [artemeff/exredis#81]
Is it possible to open multiple separate connections with this library? Right now I've got some code that runs a transaction for a HTTP request, but during the time the transaction is open other requests execute Redis commands and they also get queued in the transaction. Is there a way I can open up multiple connections?

**Comment by artemeff** [comment]
@Stratus3D you can start as many exredis clients as you want, but I would recommend you to use [Redix](https://hex.pm/packages/redix) with [poolboy](https://hex.pm/packages/poolboy) ([redix_pool](https://hex.pm/packages/redix_pool)) or just follow the instructions [here](https://github.com/whatyouhide/redix/blob/master/pages/Real-world%20usage.md#name-based-pool).

Also you can take my new library [Redis](https://hex.pm/packages/redis) for redis commands ([just take a look](https://hexdocs.pm/redis/Redis.html)!) :)

I have some ideas about redis clients adapter inside [Redis](https://hex.pm/packages/redis) library, where I can implement connection pooling too, but that thing on very early stage #79

**Comment by Stratus3D** [comment]
Thanks @artemeff, I'll give those a try.
